version: "3"
services:
  app:
    container_name: nextjs-app
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    container_name: mysql-db
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: devovo
      
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - "3307:3306"
