version: "3"
services:
  app:
    container_name: nextjs-app
    build: .
    env_file:
      - .env
    ports:
      - "${NEXTJS_PORT}:3000"
    networks:
      - mynetwork
    depends_on:
      - db
  db:
    container_name: mysql-db
    image: mysql:latest
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - "${MYSQL_PORT}:3306"
    networks:
      - mynetwork
  networks:
    mynetwork: