import MenuPrincipal from '../components/MenuPrincipal'
import Encabezado from '../components/Encabezado'
import { Inter } from 'next/font/google'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}



function RootLayout({ children, title }) {

        const userName = 'Paola Saldaña';
        const role = 'Estudiante';
        const menuTitle = 'Menú Principal';
        const color ='color-profesor';

    return (

        <html lang="en">
            <body className={inter.className} style={{backgroundColor:"#F3F6FF"}} >

                <div class="grid grid-cols-12 gap-0">
                    {/* <!-- Sidebar --> */}
        
                    <div class="col-span-2 h-full"><MenuPrincipal /></div>

                    {/* <!-- Header and container element --> */}
                    <div class="col-span-10 grid grid-rows-2 ml-12 pt-12">
                        {/* <!-- Header --> */}
                        <div class="row-span-2 pl-14 pt-5 pr-16"> 
                        <Encabezado
                        userName={userName}
                        
                         /> 
                        <div className='ContenidoDinamico'></div>
                        {children}
                        </div>

                        {/* <!-- Container element --> */}
                        
                    </div>
                </div>

               

            </body>
        </html>

    )
}

export default RootLayout;